version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    labels:
      - dependabot
      - go
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /infrastructure/pulumi
    labels:
      - dependabot
      - npm
    schedule:
      interval: daily
    versioning-strategy: increase
