version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    labels:
      - dependabot
      - go
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /infrastructure/pulumi
    labels:
      - dependabot
      - npm
    schedule:
      interval: weekly
    versioning-strategy: increase
