apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clamav-scanner.fullname" . }}
  labels:
    {{- include "clamav-scanner.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clamav-scanner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clamav-scanner.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clamav-scanner.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{- if (not (empty .Values.extraConfigMap)) }}
            - configMapRef:
                name: config-env
            {{- end }}
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: 1337
              scheme: HTTP
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 1337
              scheme: HTTP
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 1337
              scheme: HTTP
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
