replicaCount: 1

image:
  repository: ghcr.io/ignite-analytics/clamav-scanner
  pullPolicy: IfNotPresent
  digest: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: clamav-scanner

podAnnotations: {}

podSecurityContext:
  runAsUser: 100
  runAsGroup: 103
  fsGroup: 103
  fsGroupChangePolicy: "OnRootMismatch"
  seccompProfile:
    type: RuntimeDefault

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 100

poddisruptionbudget:
  enabled: true
  minAvailable: 1

service:
  type: ClusterIP
  port: 80

startupProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 30

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 1

readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 20
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 1

resources:
  limits:
    cpu: '1'
    memory: 6Gi
  requests:
    cpu: '1'
    memory: 4Gi

update:
  schedule: "37 */2 * * *"
  image:
    repository: alpine/curl
    tag: 8.5.0
  nodeSelector: {}
  tolerations:
    - effect: NoSchedule
      key: workload
      operator: Equal
      value: disruptive
  affinity: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# -- Key/value pairs to be exposed as environment variables
# @default -- `{}`
extraConfigMap:
  MIRROR_BUCKET: clamav-scanner-mirror
  QUARANTINE_BUCKET: clamav-scanner-quarantine
  LISTEN_ADDRESS: :1337
